### ISSUE TITLE
Clearer releases

### ISSUE THREAD

**Issue by rhys-vdw** [javierjulio/envied#1]
It's confusing that versions up until now don't have tags. Please put everything in master and tag each release commit (as was done in original project).

This way releases appear in the "releases"/"tags" history.

Also are there plans to publish this gem?

Also please consider moving to v1.0. Semver semantics are better defined when version is >1.

**Comment by javierjulio** [comment]
That's on purpose because these aren't necessarily final. Its a branch that is a candidate for that release as I don't have access to the actual gem. Also this allows myself and others to include the gem in their Gemfile and receive updates for that "release".

```ruby
gem 'envied', git: 'https://github.com/javierjulio/envied.git, branch: 'v0.10.0'
```

I had considered tags but I didn't see it as a complete release and also I wasn't sure if this was available through bundler. I wanted to make sure I could have a branch that can be updated if necessary. Also these are more like trial runs for that release. I wanted to have something that can be used now and have something to show to @eval to make a push for becoming a maintainer.

I'd like to be able to support the original gem. I thought of creating a new one with a different name but haven't gone that route yet.

**Comment by javierjulio** [comment]
@rhys-vdw great news. I'm now a collaborator on Envied. I'm already working on the first patch release! Expect more official releases/updates. Thanks for your activity and discussions! Keep them coming.
